/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tertiary: '#126684',
        'surface-bright': '#f9f9fc',
        'surface-dim': '#dadadc',
        error: '#ba1a1a',
        secondary: '#526522',
        'inverse-surface': '#2f3133',
        'surface-container': '#eeeef0',
        'on-secondary-container': '#566a25',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#001f2a',
        'secondary-fixed-dim': '#b8d07f',
        'on-background': '#1a1c1e',
        'surface-tint': '#006685',
        'outline-variant': '#bfc8ce',
        primary: '#006685',
        'secondary-fixed': '#d4ec99',
        background: '#f9f9fc',
        outline: '#6f787e',
        'primary-container': '#6ab7da',
        'tertiary-fixed': '#c0e8ff',
        'on-surface': '#1a1c1e',
        'primary-fixed-dim': '#84d0f4',
        'tertiary-container': '#72b6d8',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#151f00',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#8bcff2',
        'surface-container-highest': '#e2e2e5',
        'on-tertiary-fixed': '#001e2b',
        'on-error-container': '#93000a',
        'secondary-container': '#d1e996',
        'surface-container-high': '#e8e8ea',
        'on-tertiary-fixed-variant': '#004d66',
        'surface-container-low': '#f3f3f6',
        surface: '#f9f9fc',
        'on-primary-fixed-variant': '#004d65',
        'on-tertiary-container': '#00475e',
        'on-primary-container': '#00475d',
        'on-error': '#ffffff',
        'inverse-on-surface': '#f0f0f3',
        'on-secondary': '#ffffff',
        'surface-variant': '#e2e2e5',
        'inverse-primary': '#84d0f4',
        'on-secondary-fixed-variant': '#3b4d0a',
        'primary-fixed': '#bfe9ff',
        'on-surface-variant': '#3f484d',
        'on-primary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Work Sans', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
